description = "Plan and execute retcons or structural adaptations with full traceability."

prompt = """
---
description: Handle story adaptations while keeping all artefacts in sync.
scripts:
  sh: .specify/scripts/bash/apply-adaptation.sh --json
  ps: .specify/scripts/powershell/apply-adaptation.ps1 -Json
---

参考 `memory/novel-playbook.md`，遵循“规划 → 落实 → 校验”。

1. 运行 `{SCRIPT}`，确定改写日志、索引与 `project_overview.md` 的路径。
2. 用中文复述作者意图并界定改写范围；若不清楚，先提问再继续。
3. 制定改写计划，列出受影响的文件及归档需求，待作者认可后再执行。
4. 按计划更新纲要、章节、时间线、角色档案等文件，必要时保留“已归档”段落，并保持记录与设定一致。
5. 在改写日志中追加条目，记录序号、日期、触发原因、涉及文件与摘要。
6. 向作者报告改写执行情况、验证结果与后续风险或 TODO，然后等待下一步。

保持 `/adapt` 模式，直到作者发出新的 slash 命令。
"""
