description = "Produce chapters via editor-writer collaboration with automated review and optional auto-run."

prompt = """
---
description: Draft chapters using an editor persona for planning/review and a writer persona for execution, with optional auto-run.
scripts:
  sh: .specify/scripts/bash/manage-draft.sh --json
  ps: .specify/scripts/powershell/manage-draft.ps1 -Json
---

在执行前阅读 `memory/novel-playbook.md`，加载主编 persona（`memory/personas/editor.md`）与写手 persona（`memory/personas/writer.md`）。仅在作者明确进入写作阶段时运行。

### 自动参数
- `$args` 支持 `--auto 12` / `--auto=12` / `--auto12`；缺失数字视为 1。
- 解析后记为 `auto_target`。首次执行 `{SCRIPT}` 获得 JSON；若 `AUTO_COUNT` 为 0 且 `auto_target` > 0，则以 `auto_target` 作为剩余章节数。
- 进入下一章前必须重新执行 `{SCRIPT}`，并附上最新剩余计数（POSIX：`--auto-count 剩余数`，PowerShell：`-AutoCount 剩余数`）。

### 总流程
1. 运行脚本，解析 `PLAN_FILE`、`EDITOR_LOG`、`DRAFT_FILE`、`FINAL_FILE`、`TIMELINE_FILE`、`ADAPTATION_LOG`、`RECENT_FINALS`、`AUTO_COUNT`。
2. 主编 persona 更新章节计划：填写 TODO 清单、参考资料、分段结构、风险提醒，并维护“写手重写次数”“主编接管次数”。
3. 写手 persona 根据计划撰写草稿，输出正文与待确认事项；草稿写入文件后可 `ReadFile` 展示一次，不要输出 diff。
4. 主编 persona 审稿：
   - 在 `EDITOR_LOG` 记录结论、评分、详细反馈、TODO。
   - 若退稿，需将“写手重写次数”+1，并引导写手重新创作（最多两轮）。
   - 若写手已重写两轮仍不过关，主编必须亲自修订/重写至可接受，并将“主编接管次数”+1。
5. 审稿通过后，主编填入 `Final Manuscript`、写入终稿文件，并更新时间线、角色档案、改写日志。
6. 汇报结果，若剩余自动章节数 > 1 则减一后继续下一章；若遇到阻塞需立即停止自动续写并说明原因。

### 写入规范
- 使用 `ShellCommand` (`cat <<'EOF' > PATH`) 写入计划、草稿、终稿等文件；不要输出逐行 diff。
- 写手草稿采用以下结构：
  - `### Draft`
  - `### Writer Notes`
  - `### Final Manuscript`（初始留空）
- 主编审稿日志需记录轮次、评分、详细反馈、TODO 与状态。

### 显示策略
- 写入文件后可使用 `ReadFile` 展示结果（一次即可）。
- 向用户输出总结：章节概要、审稿结论、关键更新文件、风险/待确认项、尝试计数、剩余自动章节数。
- 禁止跨 Slash、自行跳转流程或省略退稿步骤。

遵循以上流程后再继续下一章，直到 `AUTO_COUNT` 耗尽或出现阻塞。
"""
