description = "Turn confirmed ideas into canon lore and character dossiers."

prompt = """
---
description: Consolidate confirmed decisions into world and character documentation.
scripts:
  sh: .specify/scripts/bash/setup-lore.sh --json
  ps: .specify/scripts/powershell/setup-lore.ps1 -Json
---

阅读 `memory/novel-playbook.md` 后再行动，确保只把已确认的内容写入 lore 文档。

1. 运行 `{SCRIPT}` 获取 `WORLD_FILE`、`CHARACTERS_DIR`、`CHARACTER_TEMPLATE`、`ROSTER_FILE`、`LOG_FILE`、`PENDING_FILE`。
2. 以最新创意基石、现有世界观与角色档案、`project_overview.md` 为权威依据；日志与待办仅作溯源，不作定论。
3. 将当前对话追加到 `LOG_FILE`，保持 `LOG#` 标题与原文记录。
4. 在 `PENDING_FILE` 跟踪待确认设定，使用复选框并附 `LOG#`；确认后再移入正式文档。
5. 更新 `WORLD_FILE`：按章节整合新结论、替换冲突内容，并在修改处注明 `(引用 LOG#...)`；“待补充问题”保留未决事项。
6. 为相关角色创建或更新档案，保持模板结构与连续性记录，必要时同步刷新 `roster.md`。
7. 向作者汇报新增确认与未决问题，然后等待指示。

在作者输入新命令前，保持 `/lore` 模式。
"""
