description = "Translate the approved concept into world-building lore and character dossiers."

prompt = """
---
description: Convert approved ideas into world lore files and character dossiers.
scripts:
  sh: .specify/scripts/bash/setup-lore.sh --json
  ps: .specify/scripts/powershell/setup-lore.ps1 -Json
---

默认情况下请使用中文与用户交流，并在写入文件时以中文记录非代码内容，除非对方明确要求使用其他语言。

当用户执行 `/lore` 时，请完成以下步骤：

1. 运行 `{SCRIPT}` 并读取 JSON，获取 `WORLD_FILE`、`CHARACTERS_DIR`、`CHARACTER_TEMPLATE`、`ROSTER_FILE` 以及 `LOG_FILE`、`PENDING_FILE`。
2. 参考 `ideas/` 会话、`project_overview.md` 与既有档案，确保设定连贯；随后将本轮讨论写入 `LOG_FILE`，标出用户输入、AI 建议与待确认条目。
3. 在 `PENDING_FILE` 中维护所有未获确认的设定、问题与行动项（使用 `[ ]` 管理）；仅在用户明确确认后，再将条目移入正式档案。
4. 只在获得确认后更新 `WORLD_FILE`，保持模板结构，并将仍未确认的内容留在 `## 待补充` 中。
5. 针对已出现或新提及的角色：
   - 若无档案，则以模板在 `CHARACTERS_DIR` 下创建对应 Markdown。
   - 补写跨时空身份、当前年龄等动态字段。
   - 在“连续性记录”表格中追加最新章节或阶段摘要。
   - 更新 `roster.md`，注明角色身份与状态（在场/待登场/退场）。
6. 用中文向用户汇报：哪些内容已确认写入档案，哪些仍在 `PENDING_FILE` 中等待确认。提出澄清问题后需暂停，待用户逐条答复。
7. 在用户输入新的 slash 指令之前，持续保持 `/lore` 模式，不触发其他脚本或跳转到 `/weave`、`/draft` 等流程。

保持档案的一致性与权威性，避免创建重复条目；如发现矛盾，请显式标注并提出建议。收到新的 slash 指令前，请持续停留在 `/lore` 模式。
"""
