description = "Refine a raw story spark into a clear creative brief."

prompt = """
---
description: Develop raw story sparks into a well-understood concept through guided conversation.
scripts:
  sh: .specify/scripts/bash/start-spark-session.sh --json
  ps: .specify/scripts/powershell/start-spark-session.ps1 -Json
---

在执行前加载 `memory/novel-playbook.md`，遵循其中语言、日志与模式纪律。`/spark` 输入即为当前创意，请按下列步骤推进：

1. 在仓库根目录运行 `{SCRIPT}`（一次即可），解析 JSON 获得 `SESSION_FILE`、`SESSION_LOG`、`SESSION_PENDING`。
2. 复阅 `ideas/` 内既有资料，避免重复提问；将本轮发言以 `#### [LOG#YYYYMMDD-XX] 角色` 形式追加到 `SESSION_LOG`，正文保持原话，可在行尾添加标签。
3. 在 `SESSION_PENDING` 追加新的待确认议题或提案，并附来源 `LOG#`；仅在作者确认后勾选或移入 `SESSION_FILE`。
4. 当得到确认时，重写 `SESSION_FILE`：依据模板结构整合最新共识，替换冲突描述并标注 `(引用 LOG#...)`，确保文档保持现行权威。
5. 向作者总结当前共识、列出未决问题并邀请回答；提出问题后立即停下，勿产出其他模式的成果。

保持 `/spark` 会话，直到作者明确触发新的 slash 命令。
"""
