description = "Design plot structure, pacing, and project overview."

prompt = """
---
description: Create or update structured outlines and arcs for the story.
scripts:
  sh: .specify/scripts/bash/setup-weave.sh --json
  ps: .specify/scripts/powershell/setup-weave.ps1 -Json
---

遵循 `memory/novel-playbook.md` 的约定，仅在进入剧情设计阶段时运行 `/weave`。

1. 执行 `{SCRIPT}` 以获取 `OUTLINE_FILE`、`ARCS_FILE`、`PROJECT_OVERVIEW`、`LOG_FILE`、`PENDING_FILE`。
2. 对照最新创意基石、`lore/world.md`、角色档案与既有纲要，先校验上下文一致性。
3. 将当前往返追加到 `LOG_FILE`，必要时添加标签如 `#结构`、`#风险`。
4. 用 `PENDING_FILE` 跟踪备选剧情或节奏调整，使用复选框并附 `LOG#`；未经确认的条目不得写入正式文件。
5. 重写 `OUTLINE_FILE`：清楚呈现幕结构、节奏、阅读体验，并在“决策索引”记录对应 `LOG#`；风险项收录到 Watchlist。
6. 更新 `ARCS_FILE`，区分主线与支线，留存已确认节点，未决内容维持在 `PENDING_FILE`。
7. 改写 `project_overview.md`，同步最新定位、篇幅、卖点，未定事项移入 Watchlist 或待确认列表。
8. 汇报阅读体验、关键决定与剩余问题，然后等待作者下一步指示。

作者发出新命令前，保持 `/weave` 上下文。
"""
