description = "Design the narrative outline, plot arcs, and update the project overview."

prompt = """
---
description: Build the plotting foundation: global outline, arcs, and project overview.
scripts:
  sh: .specify/scripts/bash/setup-weave.sh --json
  ps: .specify/scripts/powershell/setup-weave.ps1 -Json
---

默认情况下请使用中文与用户交流，并在写入文件时以中文记录非代码内容，除非对方明确要求使用其他语言。

当进入 `/weave` 阶段时，请执行以下流程：

1. 运行 `{SCRIPT}`，取得 `OUTLINE_FILE`、`ARCS_FILE`、`PROJECT_OVERVIEW` 以及 `LOG_FILE`、`PENDING_FILE` 的绝对路径。
2. 仅把以下文件视为上一阶段的确认基石：`ideas/` 中最新创意基石、`lore/world.md`、`characters/` 档案、既有 `OUTLINE_FILE`、`ARCS_FILE`、`PROJECT_OVERVIEW`。`LOG_FILE`、`PENDING_FILE` 仅用于追溯来源，禁止直接当作事实材料。
3. 复核这些基石后，阅读最新的灵感会话、`lore/world.md`、相关人物档案及旧纲要；随后以 `#### [LOG#YYYYMMDD-XX] 角色` 形式将讨论要点写入 `LOG_FILE`，并标明哪些点仍待确认。
4. 在 `PENDING_FILE` 中维护未确认的结构调整、篇章安排与节奏建议，记录对应的 `LOG#`；仅在用户确认后，才把条目写入正式纲要。
5. 以模板为蓝本改写 `OUTLINE_FILE`：
   - 重读既有内容，融合已确认的三幕结构、关键转折与章节范围；
   - 若新决定与旧内容冲突，以新决定替换，并在段尾注明 `(引用 LOG#...)`；
   - 在“节奏观察清单”中标注风险，并引用 `PENDING_FILE` 中的未决事项；
   - 在 `## 决策索引` 中登记本轮确认的要点。
6. 更新 `ARCS_FILE` 时，只整理已确认的主线/支线走向，替换冲突节点并标注 `(引用 LOG#...)`，候选走向留在 `PENDING_FILE`。
7. 重新生成 `project_overview.md`，仅纳入已确认的信息，在“决策索引”注明更新来源；仍在待确认清单中的主题或目标需保留引用。
8. 用中文向用户汇报整体阅读体验、各幕安排与待确认列表；提出问题或选项后须暂停，等待用户答复。

确保所有文档保持唯一权威、不要重复创建文件。如发现设定矛盾或风险，请在“节奏观察清单”中特别标注。收到新的 slash 指令前，一直停留在 `/weave` 模式，不启动章节写作或改稿流程。
"""
