description = "Design the narrative outline, plot arcs, and update the project overview."

prompt = """
---
description: Build the plotting foundation: global outline, arcs, and project overview.
scripts:
  sh: .specify/scripts/bash/setup-weave.sh --json
  ps: .specify/scripts/powershell/setup-weave.ps1 -Json
---

默认情况下请使用中文与用户交流，并在写入文件时以中文记录非代码内容，除非对方明确要求使用其他语言。

当进入 `/weave` 阶段时，请执行以下流程：

1. 运行 `{SCRIPT}`，取得 `OUTLINE_FILE`、`ARCS_FILE`、`PROJECT_OVERVIEW` 以及 `LOG_FILE`、`PENDING_FILE` 的绝对路径。
2. 复核上下文：阅读最新的灵感会话、`lore/world.md`、相关人物档案及旧纲要；随后将讨论要点写入 `LOG_FILE`，并标明哪些点仍待确认。
3. 在 `PENDING_FILE` 中维护未确认的结构调整、篇章安排与节奏建议；仅在用户确认后，才把条目写入正式纲要。
4. 以模板为蓝本改写 `OUTLINE_FILE`：
   - 仅记录已确认的三幕结构、关键转折与章节范围；
   - 以表格列出确认过的时间、地点、视角人物、剧情要点与钩子；
   - 在“节奏观察清单”中标注风险，并指向 `PENDING_FILE` 中的未决事项。
5. 更新 `ARCS_FILE` 时，只整理已确认的主线/支线走向；候选走向留在 `PENDING_FILE`。
6. 重新生成 `project_overview.md`，仅纳入已确认的信息，并注明仍在待确认清单中的主题或目标。
7. 用中文向用户汇报整体阅读体验、各幕安排与待确认列表；提出问题或选项后须暂停，等待用户答复。

确保所有文档保持唯一权威、不要重复创建文件。如发现设定矛盾或风险，请在“节奏观察清单”中特别标注。收到新的 slash 指令前，一直停留在 `/weave` 模式，不启动章节写作或改稿流程。
"""
